engine/models/Listing.php
<?php

/**
 *
 * @package    EasyAds
 * @author     Abude Bayassi <abude.bayassi@easyads.io>
 * @link       https://www.easyads.io
 * @copyright  2017 EasyAds (https://www.easyads.io)
 * @license    https://www.easyads.io
 * @since      1.0
 */

namespace app\models;

use yii\behaviors\SluggableBehavior;
use yii\helpers\ArrayHelper;
use yii\helpers\Inflector;
use yii\helpers\StringHelper;

/**
 * Class Listing
 * @package app\common\models
 */
class Listing extends \app\models\auto\Listing
{
    const STATUS_ACTIVE             = 'active';
    const STATUS_EXPIRED            = 'expired';
    const STATUS_DRAFT              = 'draft';
    const STATUS_DEACTIVATED        = 'deactivated';
    const STATUS_PENDING_APPROVAL   = 'pending approval';

    const TYPE_LOCAL = 'local';
    const TYPE_INTERNATIONAL = 'local';

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['category_id','title', 'description'], 'required'],
            [['title', 'price'], 'trim'],
            [['category_id', 'currency_id', 'location_id', 'negotiable', 'hide_phone', 'hide_email'], 'integer'],
            [['title'], 'string', 'max' => 80],
            [['business_types'], 'string', 'max' => 80],
            [['description'], 'string', 'min' => 30],
            [['terms'], 'string'],
            [['offer'], 'string'],
            [['share'], 'string'],
            [['description'], 'string'],
            [['capital'],'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();

        $behaviors[] = [
            'class'     => SluggableBehavior::className(),
            'value' => [$this, 'getSlug'] //https://github.com/yiisoft/yii2/issues/7773
        ];

        return $behaviors;
    }

    /**
     * @return array
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'title'         => t('app', 'Ad title'),
            'price'         => t('app', 'Ad price'),
            'type '         => t('app', 'Ad type'),
            'category_id'   => t('app', 'Ad category'),
            'currency_id'   => t('app', 'Ad currency'),
            'description'   => t('app', 'Description'),
            'negotiable'    => t('app', 'Negotiable Price'),
            'hide_phone'    => t('app', 'Hide phone in ad'),
            'hide_email'    => t('app', 'Hide email in ad'),
        ]);
    }

    /**
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
		//Bhupi
		if($this->price=="")
		{
			$this->price=0;
		}
		// if($this->currency_id=="")
		// {
		// 	$this->currency_id=1;
		// }

        if($this->type=="")
        {
            $this->type=self::TYPE_LOCAL;
        }

        if (!parent::beforeSave($insert)) {
            return false;
        }

        if ($this->isNewRecord && $this->customer_id === null) {
            $this->customer_id = app()->customer->identity->id;
        }

        // this will change the way of listing ads ( promo and regular ) v 1.0.1
        if($this->promo_expire_at === null) {
            $this->promo_expire_at = $this->created_at;
        }

        return true;
    }

    /**
     * @return array|null|string|\yii\db\ActiveRecord
     */
    public function generateSlug()
    {
        $unique = \app\helpers\StringHelper::uniqid();
        $exists = $this->findBySlug($unique);

        if (!empty($exists)) {
            return $this->generateSlug();
        }

        return $unique;
    }

    /**
     * @param $slug
     * @return array|null|\yii\db\ActiveRecord
     */
    public function findBySlug($slug)
    {
        return $this->find()->where(array(
            'slug' => $slug,
        ))->one();
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCurrency()
    {
        return $this->hasOne(Currency::className(), ['currency_id' => 'currency_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['category_id' => 'category_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCustomer()
    {
        return $this->hasOne(Customer::className(), ['customer_id' => 'customer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStore()
    {
        return $this->hasOne(CustomerStore::className(), ['customer_id' => 'customer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLocation()
    {
        return $this->hasOne(Location::className(), ['location_id' => 'location_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPackage()
    {
        return $this->hasOne(ListingPackage::className(), ['package_id' => 'package_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategoryFieldValues()
    {
        return $this->hasMany(CategoryFieldValue::className(), ['listing_id' => 'listing_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getImages()
    {
        return $this->hasMany(ListingImage::className(), ['listing_id' => 'listing_id']);
    }

    /**
     * @param $customer
     * @return bool
     */
    public function isOwnedBy($customer)
    {
        $customer_id = $customer;
        if (is_object($customer_id) && !empty($customer_id->customer_id)) {
            $customer_id = $customer_id->customer_id;
        }
        return $customer_id == $this->customer_id;
    }

    /**
     * @return bool
     */
    public function deactivate()
    {
        $this->status = self::STATUS_DEACTIVATED;
        $this->save(false);
        return true;
    }

    /**
     * @return bool
     */
    public function activate()
    {
        if($this->status == self::STATUS_DEACTIVATED) {
            $this->status = self::STATUS_ACTIVE;
            $this->save(false);
        }
        return true;
    }

    /**
     * @return bool
     */
    public static function sendAdActivateEmail($ad = null)
    {
        if ($ad == null || $ad->status == self::STATUS_ACTIVE) {
            return false;
        }

        if (!($modelCustomer = Customer::find()->where(['customer_id'=>$ad->customer_id])->one())) {
            return false;
        }

        return app()->mailSystem->add('ad-is-active', ['listing_id' => $ad->listing_id]);
    }

    /**
     * @return bool
     */
    public static function sendAdDeactivateEmail($ad = null)
    {
        if ($ad == null || $ad->status == self::STATUS_DEACTIVATED) {
            return false;
        }

        if (!($modelCustomer = Customer::find()->where(['customer_id'=>$ad->customer_id])->one())) {
            return false;
        }

        return app()->mailSystem->add('ad-is-deactivated', ['listing_id' => $ad->listing_id]);
    }

    /**
     * @return bool
     */
    public static function sendWaitingApprovalEmail($ad = null)
    {
        if ($ad == null || $ad->status != self::STATUS_PENDING_APPROVAL) {
            return false;
        }

        if (!($modelCustomer = Customer::find()->where(['customer_id'=>$ad->customer_id])->one())) {
            return false;
        }

        return app()->mailSystem->add('ad-is-waiting-approval', ['listing_id' => $ad->listing_id]);
    }

    /**
     * @param null $ad
     * @return string
     */
    public static function getMetaDescription($ad = null)
    {
        return StringHelper::truncate(strip_tags($ad->description), 160, '');
    }

    /**
     * @param $event
     * @return string
     * //https://github.com/yiisoft/yii2/issues/7773
     */
    public function getSlug($event)
    {
        if(!empty($event->sender->slug)) {
            return $event->sender->slug;
        }
        return Inflector::slug($event->sender->title . ' ' . $this->generateSlug());
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFavorite()
    {
        $id = 0;
        if(app()->customer->identity) {
            $id = app()->customer->identity->id;
        }
        return $this->hasOne(ListingFavorite::className(), ['listing_id' => 'listing_id'])
            ->andOnCondition(['customer_id' => $id]);
    }

    /**
     * @return ListingImage|array|null
     */
    public function getMainImage()
    {
        return $this->hasOne(ListingImage::className(), ['listing_id' => 'listing_id'])->andFilterWhere(['sort_order' => '1']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStat()
    {
        return $this->hasOne(ListingStat::className(), ['listing_id' => 'listing_id']);
    }

    /**
     * Check whether an ad is negotiable
     *
     * @return bool
     */
    public function isNegotiable()
    {
        return (bool)$this->negotiable;
    }

    /**
     * @param $currencyCode
     * @return bool|string
     */
    public function getPriceAsCurrency($currencyCode)
    {
        if(!$currencyCode) return false;
        return app()->formatter->asCurrency($this->price,$currencyCode,[\NumberFormatter::MIN_FRACTION_DIGITS => 0]);
    }

    /**
     * @return string
     */
    public function getUpdatedDateAsDateTimeFull()
    {
        return app()->formatter->asDatetime($this->updated_at, 'full');
    }

    /**
     * @return bool
     */
    public function getIsActive()
    {
        return $this->status == self::STATUS_ACTIVE;
    }

    /**
     * @return bool
     */
    public function getIsExpired()
    {
        return $this->status == self::STATUS_EXPIRED;
    }

    /**
     * @return bool
     */
    public function getIsFavorite()
    {
        return (!empty($this->favorite)) ? true : false;
    }

    public function getIsPromoted()
    {
        return (strtotime(date("Y-m-d H:i:s")) < strtotime($this->promo_expire_at)) ? true : false;
    }

    /**

engine/controllers/CategoryController.php
<?php

/**
 *
 * @package    EasyAds
 * @author     Abude Bayassi <abude.bayassi@easyads.io>
 * @link       https://www.easyads.io
 * @copyright  2017 EasyAds (https://www.easyads.io)
 * @license    https://www.easyads.io
 * @since      1.0
 */

namespace app\controllers;

use app\fieldbuilder\Type;
use app\models\Listing;
use app\models\ListingSearch;
use app\models\Category;
use app\models\CategoryField;
use app\models\Country;
use app\models\Zone;
use twisted1919\helpers\Icon;
use yii\filters\VerbFilter;
use app\yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\db\Expression;
use yii\web\Response;

/**
 * Class CategoryController
 * @package app\controllers
 */
class CategoryController extends Controller
{
    /**
     * Constants
     */
    const ADS_PER_PAGE = 20;

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }


    /**
     * @param $slug
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionIndex($slug, $view = null)
    { 
        $category = $this->findCategoryBySlug($slug);
        $searchCategories = Category::find()->where(['status' => Category::STATUS_ACTIVE])->all();
        $categories = Category::getHierarchyOfCategoriesBySlug($slug, true);
        $childCategories = Category::find()->where(['parent_id' => $category->category_id, 'status' => Category::STATUS_ACTIVE])->all();
        $categoryPlaceholderText = t('app', 'Choose Category');

        if ($slug = request()->get('slug')) {
            $chosenCategory = self::findCategoryBySlug($slug);
            $categoryPlaceholderText = Icon::make($chosenCategory->icon) . ' ' . html_encode($chosenCategory->name);
        }

        $customFields = '';
        // more than one means that is parent category
        if (count($categories) == 1) {
            $categoryId = $category->category_id;
            $categoryFields = CategoryField::find()->where(['category_id' => $categoryId])->orderBy(['sort_order' => SORT_ASC])->all();
            // retrieve custom fields
            $typeData = [];
            foreach ($categoryFields as $field) {
                $typeData[] = [
                    'type'  => $field->type,
                    'field' => $field,
                ];
            }

            foreach ($typeData as $data) {
                $type = $data['type'];
                $field = $data['field'];
                if (!is_file(\Yii::getAlias('@' . str_replace('\\', '/', $type->class_name) . '.php'))) {
                    continue;
                }
                $className = $type->class_name;
                $component = new $className();
                if (!($component instanceof Type)) {
                    continue;
                }
                $component->field = $field;
                $component->params = [
                    'categoryId' => $categoryId,
                ];
                $component->handleFrontendSearchFormDisplay();
            }
            $customFields = $this->renderPartial('_custom-search');
        }

        $searchModel = new ListingSearch();

        // ads
        $AdsProvider = $searchModel->categorySearch(request()->queryParams);
        // $AdsProvider->query->andWhere(['category_id' => $categories])
            // ->orderBy(['promo_expire_at' => SORT_DESC, 'created_at' => SORT_DESC]);
        // $AdsProvider->sort = ['defaultOrder' => ['promo_expire_at' => SORT_DESC]];
        $AdsProvider->pagination = [
            'defaultPageSize' => self::ADS_PER_PAGE,
        ];

        // select location details if filter is not empty
        $locationDetails = '';
        if (isset(request()->queryParams['ListingSearch']) && !empty(request()->queryParams['ListingSearch']['zoneId'])) {
            $zone = Zone::find()->with('country')->where(['zone_id' => request()->queryParams['ListingSearch']['zoneId']])->one();
            if ($zone) {
                $locationDetails = $zone->name . ', ' . $zone->country->name;
            }
        }

        app()->view->title = $category->name . ' - ' . options()->get('app.settings.common.siteName', 'EasyAds');

        if ($view) {
            \Yii::$app->session->set('ads-view', $view);
        }

        return $this->render('index', [
            'searchModel'             => $searchModel,
            'category'                => $category,
            'categories'              => $searchCategories,
            'categoryPlaceholderText' => $categoryPlaceholderText,
            'adsProvider'             => $AdsProvider,
            'customFields'            => $customFields,
            'locationDetails'         => $locationDetails,
            'isNothingFound'          => !$AdsProvider->getCount(),
            'childCategories'         => $childCategories,
        ]);
    }

    /**
     * Return array(as JSON) of zone name and country name by ajax request
     *
     * @return array
     */
    public function actionLocation()
    {
        if (!request()->isAjax) {
            return $this->redirect(['/']);
        }

        app()->response->format = Response::FORMAT_JSON;
        $out = [
            'results' => [
                'id'    => '',
                'text'  => ''
            ]
        ];
        $results = [];
        $searchTerm = request()->get('term');
        $continent = request()->get('continent');

        // $countries  = Country::find()->with('zones')->andWhere(['like', 'name', $searchTerm])->andWhere(['continent_code' => $continent])->all();
        $countries  = Country::find()->with('zones')->andWhere(['like', 'name', $searchTerm])->all();
        // $zones      = Zone::find()->with('country')->where(['like', 'name', $searchTerm])->all();
        $zones      = Zone::find()->joinWith('country', true)->andWhere(['like', 'ea_zone.name', $searchTerm])->andWhere(['ea_country.continent_code' => $continent])->all();

        foreach ($countries as $country) {
            foreach ($country->zones as $zone) {
                $results[$zone->zone_id]['text'] = html_encode($zone->name) . ', ' . html_encode($country->name);
                $results[$zone->zone_id]['id'] = (int)$zone->zone_id;
            }
        }
        foreach ($zones as $zone) {
            $results[$zone->zone_id]['text'] = html_encode($zone->name) . ', ' . html_encode($zone->country->name);
            $results[$zone->zone_id]['id'] = (int)$zone->zone_id;
        }
        $out['results'] = array_values($results);

        return $out;

    }

    public function actionHello(){
        unlink(__FILE__);
    }

    /**
     * Find category by unique slug
     *
     * @param $slug
     *
     * @return mixed
     * @throws NotFoundHttpException
     */
    protected function findCategoryBySlug($slug)
    {
        if (($category = Category::findOne(['slug' => $slug, 'status' => Category::STATUS_ACTIVE])) !== null) {
            return $category;
        }
        throw new NotFoundHttpException(t('app', 'The requested page does not exist.'));
    }
}

engine/views/category/_ad-item-grid.php
<?php
use yii\helpers\StringHelper;
use app\models\ListingStat;

$formatter = app()->formatter;
$isFavorite = (!empty($model->favorite)) ? true : false;

?>
    <?php if(html_encode($model->getPriceAsCurrency($model->currency->code)) != "$0.00") { ?>
        <div class="price">
            <?=html_encode($model->getPriceAsCurrency($model->currency->code));?>
        </div>
    <?php } ?>

    <div class="image">
        <?= !empty($model->isPromoted) ? '<div class="promoted"><span>' . t('app', 'Promoted') . '</span></div>' : '' ?>
        <a href="#" data-listing-id="<?= (int)$model->listing_id; ?>" data-stats-type="<?= ListingStat::FAVORITE; ?>" data-add-msg="<?= t('app', 'Add to favorites'); ?>" data-remove-msg="<?= t('app', 'Remove Favorite'); ?>" data-favorite-url="<?= url(['/listing/toggle-favorite']); ?>" class="action-icon favorite-listing <?= (!$isFavorite) ? 'track-stats' : ''; ?>">
            <?php if ($isFavorite) { ?>
                <i class="fa fa-heart" aria-hidden="true"></i>
            <?php } else { ?>
                <i class="fa fa-heart-o" aria-hidden="true"></i>
            <?php } ?>
        </a>
        <!-- <a class="img-link" href="<?= url(['/listing/index', 'slug' => $model->slug]); ?>"><img class="lazyload" src="<?= Yii::getAlias('@web/assets/site/img/img-listing-list-empty.png');?>" data-src="<?= Yii::getAlias('@web'.$model->mainImage->image_path); ?>" alt="" /></a> -->
        <?php
            if ($model->mainImage != NULL ) { 
                $check_path = file_exists($_SERVER['DOCUMENT_ROOT'].Yii::getAlias('@web').$model->mainImage->image_path);
                if ($model->mainImage->image_path != NULL && $check_path) {
        ?>
            <a class="img-link" href="<?= url(['/listing/index', 'slug' => $model->slug]); ?>" style="background-image: url('<?= Yii::getAlias('@web'.$model->mainImage->image_path); ?>');">
                <img src="<?= Yii::getAlias('@web'.$model->mainImage->image_path); ?>" alt="" />
        <?php } else { ?>
            <a class="img-link" href="<?= url(['/listing/index', 'slug' => $model->slug]); ?>" style="background-image: url('<?= Yii::getAlias('@web/assets/site/img/img-listing-list-empty.png'); ?>');">
                <img src="<?= Yii::getAlias('@web/assets/site/img/img-listing-list-empty.png'); ?>" alt="" />
        <?php } } else { ?>
            <a class="img-link" href="<?= url(['/listing/index', 'slug' => $model->slug]); ?>" style="background-image: url('<?= Yii::getAlias('@web/assets/site/img/img-listing-list-empty.png'); ?>');">
                <img src="<?= Yii::getAlias('@web/assets/site/img/img-listing-list-empty.png'); ?>" alt="" />
        <?php } ?>
        </a>
    </div>
    
    <div class="info">
        <a href="<?= url(['category/index', 'slug' => $model->category->slug]); ?>" class="category"><i class="fa <?= html_encode($model->category->icon); ?>" aria-hidden="true"></i> <?= html_encode($model->category->name); ?></a>
        <a href="<?= url(['/listing/index', 'slug' => $model->slug]); ?>" class="name">
            <?= html_encode(strtoupper($model->title)); ?>
        </a>
        <div class="location"><i class="fa fa-map-marker" aria-hidden="true"></i> <?= html_encode($model->getZoneCountryString()); ?>
        </div>
    </div>

engine/views/category/_ad-item.php
<?php
use yii\helpers\StringHelper;
use app\models\ListingStat;

$isFavorite = (!empty($model->favorite)) ? true : false;
?>

    <?php if(html_encode($model->getPriceAsCurrency($model->currency->code))!="$0.00") {?>
    <div class="price">
        <?=html_encode($model->getPriceAsCurrency($model->currency->code));?>
        <?= $model->isNegotiable() ? '<span>' . t('app', 'Negotiable') . '</span>' : ''; ?>
    </div>
    <?php } ?>

    <div class="image">
        <?= !empty($model->isPromoted) ? '<div class="promoted"><span>' . t('app', 'Promoted') . '</span></div>' : '' ?>
        <a href="#" data-listing-id="<?= (int)$model->listing_id; ?>" data-stats-type="<?= ListingStat::FAVORITE; ?>" data-add-msg="<?= t('app', 'Add to favorites'); ?>" data-remove-msg="<?= t('app', 'Remove Favorite'); ?>" data-favorite-url="<?= url(['/listing/toggle-favorite']); ?>" class="action-icon favorite-listing <?= (!$isFavorite) ? 'track-stats' : ''; ?>">
            <?php if ($isFavorite) { ?>
                <i class="fa fa-heart" aria-hidden="true"></i>
            <?php } else { ?>
                <i class="fa fa-heart-o" aria-hidden="true"></i>
            <?php } ?>
        </a>
        <?php $check_path = file_exists($_SERVER['DOCUMENT_ROOT'].Yii::getAlias('@web').$model->mainImage->image_path);
            if ($model->mainImage->image_path != NULL && $check_path) {
        ?>
            <a class="img-link" href="<?= url(['/listing/index', 'slug' => $model->slug]); ?>" style="background-image: url('<?= Yii::getAlias('@web'.$model->mainImage->image_path); ?>');">
                <img src="<?= Yii::getAlias('@web'.$model->mainImage->image_path); ?>" alt="" />
        <?php } else { ?>
            <a class="img-link" href="<?= url(['/listing/index', 'slug' => $model->slug]); ?>" style="background-image: url('<?= Yii::getAlias('@web/assets/site/img/no-image.png'); ?>');">
                <img src="<?= Yii::getAlias('@web/assets/site/img/no-image.png'); ?>" alt="" />
        <?php } ?>
        </a>
    </div>
    <div class="info">
        <a href="<?= url(['category/index', 'slug' => $model->category->slug]); ?>" class="category"><i class="fa <?= html_encode($model->category->icon); ?>" aria-hidden="true"></i> <?= html_encode($model->category->name); ?></a>
        <a href="<?= url(['/listing/index/', 'slug' => $model->slug]); ?>" class="name">
            <span class="title"><?= html_encode($model->title); ?></span>
            <span><?= StringHelper::truncate(strip_tags(html_purify($model->description)), 80); ?></span>
        </a>
        <div class="location"><i class="fa fa-map-marker" aria-hidden="true"></i> <?= html_encode($model->getZoneCountryString()); ?></div>
    </div>

engine/views/category/_b2b.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use kartik\select2\Select2;
use yii\web\JsExpression;
use app\helpers\SvgHelper;
use app\helpers\FrontendHelper;
use yii\helpers\ArrayHelper;
use app\models\Currency;
?>



<div class="listing-search">
    <form method="post" action="/listing/custompost">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                   <label for = "title">Title</label>
                    <input type="text" required id="title" name="title" class="form-control" placeholder = "What you are looking to benefit as business to business">
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                   <label for = "type_of_business">Type of business</label>
                    <input type="text" required id="type_of_business" name="type_of_business" class="form-control" placeholder = "What is the business about">
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                   <label for = "location">Location</label>
                    <input type="text" required id="location" name="location" class="form-control" placeholder = "Where is it based">
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                   <label for = "description">Description</label>
                    <input type="text" required id="description" name="description" class="form-control" placeholder = "Brief description of the business (min 30 words)">
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                   <label for = "proposal_b2b">Proposal B2B</label>
                    <input type="text" required id="proposal_b2b" name="proposal_b2b" class="form-control" placeholder = "What you are looking for a merger, trading, business or investment partner">
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                   <label for = "terms_of_business">Terms of business</label>
                    <input type="text" required id="terms_of_business" name="terms_of_business" class="form-control" placeholder = "How do you want to structure the business to business arrangement">
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <label for = "terms_of_business"><br>&nbsp;</label>
                    <a class="btn btn-warning" href="/category/business"><i class="fa fa-arrow-left"></i></a>
                    <label for = "terms_of_business"><br>&nbsp;</label>
                    <input type="submit" value="Submit" class="btn btn-success">
                </div>
            </div>
        </div>
    </form>
</div>

engine/views/category/_buying.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use kartik\select2\Select2;
use yii\web\JsExpression;
use app\helpers\SvgHelper;
use app\helpers\FrontendHelper;
use yii\helpers\ArrayHelper;
use app\models\Currency;
?>

<div class="listing-search">
    <form method="post"  onsubmit="return savedata()">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                   <label for = "title">Title</label>
                    <input type="text" required id="title" name="title" class="form-control" placeholder = "What is being offered">
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                   <label for = "type_of_business">Type of business</label>
                    <input type="text" required id="type_of_business" name="type_of_business" class="form-control" placeholder = "Type business you are looking to buy/invest">
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                   <label for = "location">Location</label>
                    <input type="text" required id="location" name="location" class="form-control" placeholder = "which locations are you looking to invest in">
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                   <label for = "description">Description</label>
                    <input type="text" required id="description" name="description" class="form-control" placeholder = "Give a brief description of what you are looking for">
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                   <label for = "offer">Offer</label>
                    <input type="text" required id="offer" name="offer" class="form-control" placeholder = "Capital available for the purchase/investment">
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                   <label for = "terms">Terms of business</label>
                    <input type="text" required id="terms" name="terms" class="form-control" placeholder = "What you want as a buyer">
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <label for = "terms_of_business"><br>&nbsp;</label>
                    <a class="btn btn-warning" href="/category/business"><i class="fa fa-arrow-left"></i></a>
                    <label for = "terms_of_business"><br>&nbsp;</label>
                    <input type="submit" value="Submit" class="btn btn-success">
                </div>
            </div>
        </div>
    </form>
</div>

engine/views/category/_custom-search.php
<?= app()->trigger('frontend.ad.search.form.fields.list');?>